from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1400, 900)        
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")        
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")       
        self.title_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.title_label.setFont(font)
        self.title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.title_label.setObjectName("title_label")
        self.verticalLayout.addWidget(self.title_label)        
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")        
        self.tab_dashboard = QtWidgets.QWidget()
        self.tab_dashboard.setObjectName("tab_dashboard")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_dashboard)
        self.verticalLayout_2.setObjectName("verticalLayout_2")        
        self.stats_group = QtWidgets.QGroupBox(self.tab_dashboard)
        self.stats_group.setObjectName("stats_group")
        self.gridLayout = QtWidgets.QGridLayout(self.stats_group)
        self.gridLayout.setObjectName("gridLayout")        
        self.total_users_card = QtWidgets.QGroupBox(self.stats_group)
        self.total_users_card.setObjectName("total_users_card")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.total_users_card)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.total_users_value = QtWidgets.QLabel(self.total_users_card)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.total_users_value.setFont(font)
        self.total_users_value.setAlignment(QtCore.Qt.AlignCenter)
        self.total_users_value.setObjectName("total_users_value")
        self.verticalLayout_3.addWidget(self.total_users_value)
        self.gridLayout.addWidget(self.total_users_card, 0, 0, 1, 1)
        
        self.active_users_card = QtWidgets.QGroupBox(self.stats_group)
        self.active_users_card.setObjectName("active_users_card")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.active_users_card)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.active_users_value = QtWidgets.QLabel(self.active_users_card)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.active_users_value.setFont(font)
        self.active_users_value.setAlignment(QtCore.Qt.AlignCenter)
        self.active_users_value.setObjectName("active_users_value")
        self.verticalLayout_4.addWidget(self.active_users_value)
        self.gridLayout.addWidget(self.active_users_card, 0, 1, 1, 1)        
        self.banned_users_card = QtWidgets.QGroupBox(self.stats_group)
        self.banned_users_card.setObjectName("banned_users_card")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.banned_users_card)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.banned_users_value = QtWidgets.QLabel(self.banned_users_card)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.banned_users_value.setFont(font)
        self.banned_users_value.setAlignment(QtCore.Qt.AlignCenter)
        self.banned_users_value.setObjectName("banned_users_value")
        self.verticalLayout_5.addWidget(self.banned_users_value)
        self.gridLayout.addWidget(self.banned_users_card, 0, 2, 1, 1)        
        self.total_points_card = QtWidgets.QGroupBox(self.stats_group)
        self.total_points_card.setObjectName("total_points_card")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.total_points_card)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.total_points_value = QtWidgets.QLabel(self.total_points_card)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.total_points_value.setFont(font)
        self.total_points_value.setAlignment(QtCore.Qt.AlignCenter)
        self.total_points_value.setObjectName("total_points_value")
        self.verticalLayout_6.addWidget(self.total_points_value)
        self.gridLayout.addWidget(self.total_points_card, 1, 0, 1, 1)        
        self.total_games_card = QtWidgets.QGroupBox(self.stats_group)
        self.total_games_card.setObjectName("total_games_card")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.total_games_card)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.total_games_value = QtWidgets.QLabel(self.total_games_card)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.total_games_value.setFont(font)
        self.total_games_value.setAlignment(QtCore.Qt.AlignCenter)
        self.total_games_value.setObjectName("total_games_value")
        self.verticalLayout_7.addWidget(self.total_games_value)
        self.gridLayout.addWidget(self.total_games_card, 1, 1, 1, 1)        
        self.total_questions_card = QtWidgets.QGroupBox(self.stats_group)
        self.total_questions_card.setObjectName("total_questions_card")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.total_questions_card)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.total_questions_value = QtWidgets.QLabel(self.total_questions_card)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.total_questions_value.setFont(font)
        self.total_questions_value.setAlignment(QtCore.Qt.AlignCenter)
        self.total_questions_value.setObjectName("total_questions_value")
        self.verticalLayout_8.addWidget(self.total_questions_value)
        self.gridLayout.addWidget(self.total_questions_card, 1, 2, 1, 1)        
        self.correct_answers_card = QtWidgets.QGroupBox(self.stats_group)
        self.correct_answers_card.setObjectName("correct_answers_card")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.correct_answers_card)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.correct_answers_value = QtWidgets.QLabel(self.correct_answers_card)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.correct_answers_value.setFont(font)
        self.correct_answers_value.setAlignment(QtCore.Qt.AlignCenter)
        self.correct_answers_value.setObjectName("correct_answers_value")
        self.verticalLayout_9.addWidget(self.correct_answers_value)
        self.gridLayout.addWidget(self.correct_answers_card, 2, 0, 1, 1)       
        self.avg_accuracy_card = QtWidgets.QGroupBox(self.stats_group)
        self.avg_accuracy_card.setObjectName("avg_accuracy_card")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.avg_accuracy_card)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.avg_accuracy_value = QtWidgets.QLabel(self.avg_accuracy_card)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.avg_accuracy_value.setFont(font)
        self.avg_accuracy_value.setAlignment(QtCore.Qt.AlignCenter)
        self.avg_accuracy_value.setObjectName("avg_accuracy_value")
        self.verticalLayout_10.addWidget(self.avg_accuracy_value)
        self.gridLayout.addWidget(self.avg_accuracy_card, 2, 1, 1, 1)        
        self.verticalLayout_2.addWidget(self.stats_group)        
        self.actions_group = QtWidgets.QGroupBox(self.tab_dashboard)
        self.actions_group.setObjectName("actions_group")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.actions_group)
        self.horizontalLayout.setObjectName("horizontalLayout")        
        self.refresh_stats_btn = QtWidgets.QPushButton(self.actions_group)
        self.refresh_stats_btn.setObjectName("refresh_stats_btn")
        self.horizontalLayout.addWidget(self.refresh_stats_btn)       
        self.add_question_btn = QtWidgets.QPushButton(self.actions_group)
        self.add_question_btn.setObjectName("add_question_btn")
        self.horizontalLayout.addWidget(self.add_question_btn)        
        self.broadcast_btn = QtWidgets.QPushButton(self.actions_group)
        self.broadcast_btn.setObjectName("broadcast_btn")
        self.horizontalLayout.addWidget(self.broadcast_btn)        
        self.stats_btn = QtWidgets.QPushButton(self.actions_group)
        self.stats_btn.setObjectName("stats_btn")
        self.horizontalLayout.addWidget(self.stats_btn)      

        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)        
        self.verticalLayout_2.addWidget(self.actions_group)        
        self.activity_group = QtWidgets.QGroupBox(self.tab_dashboard)
        self.activity_group.setObjectName("activity_group")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.activity_group)
        self.verticalLayout_11.setObjectName("verticalLayout_11")        
        self.activity_label = QtWidgets.QLabel(self.activity_group)
        self.activity_label.setWordWrap(True)
        self.activity_label.setObjectName("activity_label")
        self.verticalLayout_11.addWidget(self.activity_label)        
        self.verticalLayout_2.addWidget(self.activity_group)        
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)        
        self.tabWidget.addTab(self.tab_dashboard, "")        
        self.tab_questions = QtWidgets.QWidget()
        self.tab_questions.setObjectName("tab_questions")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.tab_questions)
        self.verticalLayout_12.setObjectName("verticalLayout_12")        
        self.control_group = QtWidgets.QGroupBox(self.tab_questions)
        self.control_group.setObjectName("control_group")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.control_group)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")        
        self.add_question_btn_2 = QtWidgets.QPushButton(self.control_group)
        self.add_question_btn_2.setObjectName("add_question_btn_2")
        self.horizontalLayout_2.addWidget(self.add_question_btn_2)        
        self.edit_question_btn = QtWidgets.QPushButton(self.control_group)
        self.edit_question_btn.setObjectName("edit_question_btn")
        self.horizontalLayout_2.addWidget(self.edit_question_btn)        
        self.delete_question_btn = QtWidgets.QPushButton(self.control_group)
        self.delete_question_btn.setObjectName("delete_question_btn")
        self.horizontalLayout_2.addWidget(self.delete_question_btn)        
        self.refresh_questions_btn = QtWidgets.QPushButton(self.control_group)
        self.refresh_questions_btn.setObjectName("refresh_questions_btn")
        self.horizontalLayout_2.addWidget(self.refresh_questions_btn)        
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)        
        self.verticalLayout_12.addWidget(self.control_group)        
        self.search_group = QtWidgets.QGroupBox(self.tab_questions)
        self.search_group.setObjectName("search_group")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.search_group)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")        
        self.search_label = QtWidgets.QLabel(self.search_group)
        self.search_label.setObjectName("search_label")
        self.horizontalLayout_3.addWidget(self.search_label)        
        self.question_search_input = QtWidgets.QLineEdit(self.search_group)
        self.question_search_input.setObjectName("question_search_input")
        self.horizontalLayout_3.addWidget(self.question_search_input)        
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)       
        self.verticalLayout_12.addWidget(self.search_group)        
        self.questions_table = QtWidgets.QTableWidget(self.tab_questions)
        self.questions_table.setObjectName("questions_table")
        self.questions_table.setColumnCount(7)
        self.verticalLayout_12.addWidget(self.questions_table)        
        self.tabWidget.addTab(self.tab_questions, "")        
        self.tab_users = QtWidgets.QWidget()
        self.tab_users.setObjectName("tab_users")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.tab_users)
        self.verticalLayout_13.setObjectName("verticalLayout_13")        
        self.search_group_2 = QtWidgets.QGroupBox(self.tab_users)
        self.search_group_2.setObjectName("search_group_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.search_group_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")        
        self.search_label_2 = QtWidgets.QLabel(self.search_group_2)
        self.search_label_2.setObjectName("search_label_2")
        self.horizontalLayout_4.addWidget(self.search_label_2)        
        self.user_search_input = QtWidgets.QLineEdit(self.search_group_2)
        self.user_search_input.setObjectName("user_search_input")
        self.horizontalLayout_4.addWidget(self.user_search_input)        
        self.user_search_btn = QtWidgets.QPushButton(self.search_group_2)
        self.user_search_btn.setObjectName("user_search_btn")
        self.horizontalLayout_4.addWidget(self.user_search_btn)        
        self.show_all_users_btn = QtWidgets.QPushButton(self.search_group_2)
        self.show_all_users_btn.setObjectName("show_all_users_btn")
        self.horizontalLayout_4.addWidget(self.show_all_users_btn)        
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)        
        self.verticalLayout_13.addWidget(self.search_group_2)        
        self.users_table = QtWidgets.QTableWidget(self.tab_users)
        self.users_table.setObjectName("users_table")
        self.users_table.setColumnCount(6)
        self.verticalLayout_13.addWidget(self.users_table)        
        self.user_actions_layout = QtWidgets.QHBoxLayout()
        self.user_actions_layout.setObjectName("user_actions_layout")        
        self.manage_user_btn = QtWidgets.QPushButton(self.tab_users)
        self.manage_user_btn.setObjectName("manage_user_btn")
        self.user_actions_layout.addWidget(self.manage_user_btn)        
        self.ban_user_btn = QtWidgets.QPushButton(self.tab_users)
        self.ban_user_btn.setObjectName("ban_user_btn")
        self.user_actions_layout.addWidget(self.ban_user_btn)        
        self.unban_user_btn = QtWidgets.QPushButton(self.tab_users)
        self.unban_user_btn.setObjectName("unban_user_btn")
        self.user_actions_layout.addWidget(self.unban_user_btn)        
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.user_actions_layout.addItem(spacerItem5)        
        self.verticalLayout_13.addLayout(self.user_actions_layout)        
        self.tabWidget.addTab(self.tab_users, "")        
        self.tab_broadcast = QtWidgets.QWidget()
        self.tab_broadcast.setObjectName("tab_broadcast")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.tab_broadcast)
        self.verticalLayout_14.setObjectName("verticalLayout_14")        
        self.message_group = QtWidgets.QGroupBox(self.tab_broadcast)
        self.message_group.setObjectName("message_group")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.message_group)
        self.verticalLayout_15.setObjectName("verticalLayout_15")        
        self.broadcast_message_input = QtWidgets.QTextEdit(self.message_group)
        self.broadcast_message_input.setMaximumSize(QtCore.QSize(16777215, 150))
        self.broadcast_message_input.setObjectName("broadcast_message_input")
        self.verticalLayout_15.addWidget(self.broadcast_message_input)        
        self.verticalLayout_14.addWidget(self.message_group)        
        self.control_group_2 = QtWidgets.QGroupBox(self.tab_broadcast)
        self.control_group_2.setObjectName("control_group_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.control_group_2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")        
        self.start_broadcast_btn = QtWidgets.QPushButton(self.control_group_2)
        self.start_broadcast_btn.setObjectName("start_broadcast_btn")
        self.horizontalLayout_5.addWidget(self.start_broadcast_btn)        
        self.stop_broadcast_btn = QtWidgets.QPushButton(self.control_group_2)
        self.stop_broadcast_btn.setObjectName("stop_broadcast_btn")
        self.horizontalLayout_5.addWidget(self.stop_broadcast_btn)        
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)        
        self.verticalLayout_14.addWidget(self.control_group_2)        
        self.progress_group = QtWidgets.QGroupBox(self.tab_broadcast)
        self.progress_group.setObjectName("progress_group")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.progress_group)
        self.verticalLayout_16.setObjectName("verticalLayout_16")        
        self.broadcast_progress = QtWidgets.QProgressBar(self.progress_group)
        self.broadcast_progress.setProperty("value", 0)
        self.broadcast_progress.setObjectName("broadcast_progress")
        self.verticalLayout_16.addWidget(self.broadcast_progress)        
        self.broadcast_status = QtWidgets.QLabel(self.progress_group)
        self.broadcast_status.setObjectName("broadcast_status")
        self.verticalLayout_16.addWidget(self.broadcast_status)        
        self.verticalLayout_14.addWidget(self.progress_group)        
        self.results_group = QtWidgets.QGroupBox(self.tab_broadcast)
        self.results_group.setObjectName("results_group")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.results_group)
        self.verticalLayout_17.setObjectName("verticalLayout_17")        
        self.broadcast_results = QtWidgets.QTextEdit(self.results_group)
        self.broadcast_results.setMaximumSize(QtCore.QSize(16777215, 200))
        self.broadcast_results.setObjectName("broadcast_results")
        self.verticalLayout_17.addWidget(self.broadcast_results)        
        self.verticalLayout_14.addWidget(self.results_group)        
        self.tabWidget.addTab(self.tab_broadcast, "")        
        self.tab_statistics = QtWidgets.QWidget()
        self.tab_statistics.setObjectName("tab_statistics")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.tab_statistics)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.tabWidget.addTab(self.tab_statistics, "")        
        self.tab_ai_dialogs = QtWidgets.QWidget()
        self.tab_ai_dialogs.setObjectName("tab_ai_dialogs")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.tab_ai_dialogs)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.tabWidget.addTab(self.tab_ai_dialogs, "")        
        self.tab_ai_feedback = QtWidgets.QWidget()
        self.tab_ai_feedback.setObjectName("tab_ai_feedback")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.tab_ai_feedback)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.tabWidget.addTab(self.tab_ai_feedback, "")        
        self.tab_settings = QtWidgets.QWidget()
        self.tab_settings.setObjectName("tab_settings")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.tab_settings)
        self.verticalLayout_21.setObjectName("verticalLayout_21")        
        self.bot_settings_group = QtWidgets.QGroupBox(self.tab_settings)
        self.bot_settings_group.setObjectName("bot_settings_group")
        self.formLayout = QtWidgets.QFormLayout(self.bot_settings_group)
        self.formLayout.setObjectName("formLayout")        
        self.bot_token_label = QtWidgets.QLabel(self.bot_settings_group)
        self.bot_token_label.setObjectName("bot_token_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.bot_token_label)        
        self.bot_token_input = QtWidgets.QLineEdit(self.bot_settings_group)
        self.bot_token_input.setObjectName("bot_token_input")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.bot_token_input)        
        self.admin_ids_label = QtWidgets.QLabel(self.bot_settings_group)
        self.admin_ids_label.setObjectName("admin_ids_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.admin_ids_label)        
        self.admin_ids_input = QtWidgets.QLineEdit(self.bot_settings_group)
        self.admin_ids_input.setObjectName("admin_ids_input")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.admin_ids_input)        
        self.verticalLayout_21.addWidget(self.bot_settings_group)        
        self.db_group = QtWidgets.QGroupBox(self.tab_settings)
        self.db_group.setObjectName("db_group")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.db_group)
        self.verticalLayout_22.setObjectName("verticalLayout_22")       
        self.backup_db_btn = QtWidgets.QPushButton(self.db_group)
        self.backup_db_btn.setObjectName("backup_db_btn")
        self.verticalLayout_22.addWidget(self.backup_db_btn)        
        self.create_admin_btn = QtWidgets.QPushButton(self.db_group)
        self.create_admin_btn.setObjectName("create_admin_btn")
        self.verticalLayout_22.addWidget(self.create_admin_btn)        
        self.verticalLayout_21.addWidget(self.db_group)        
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_21.addItem(spacerItem7)        
        self.tabWidget.addTab(self.tab_settings, "")        
        self.verticalLayout.addWidget(self.tabWidget)       
        MainWindow.setCentralWidget(self.centralwidget)        
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1400, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)        
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Telegram Bot Admin Panel"))
        self.title_label.setText(_translate("MainWindow", "Панель управления Telegram ботом"))
        self.stats_group.setTitle(_translate("MainWindow", "📊 Общая статистика"))
        self.total_users_card.setTitle(_translate("MainWindow", "👥 Всего пользователей"))
        self.total_users_value.setText(_translate("MainWindow", "0"))
        self.active_users_card.setTitle(_translate("MainWindow", "🔥 Активных"))
        self.active_users_value.setText(_translate("MainWindow", "0"))
        self.banned_users_card.setTitle(_translate("MainWindow", "🚫 Заблокированных"))
        self.banned_users_value.setText(_translate("MainWindow", "0"))
        self.total_points_card.setTitle(_translate("MainWindow", "⭐ Всего баллов"))
        self.total_points_value.setText(_translate("MainWindow", "0"))
        self.total_games_card.setTitle(_translate("MainWindow", "🎮 Всего игр"))
        self.total_games_value.setText(_translate("MainWindow", "0"))
        self.total_questions_card.setTitle(_translate("MainWindow", "❓ Всего вопросов"))
        self.total_questions_value.setText(_translate("MainWindow", "0"))
        self.correct_answers_card.setTitle(_translate("MainWindow", "✅ Правильных ответов"))
        self.correct_answers_value.setText(_translate("MainWindow", "0"))
        self.avg_accuracy_card.setTitle(_translate("MainWindow", "📈 Средняя точность"))
        self.avg_accuracy_value.setText(_translate("MainWindow", "0"))
        self.actions_group.setTitle(_translate("MainWindow", "⚡ Быстрые действия"))
        self.refresh_stats_btn.setText(_translate("MainWindow", "🔄 Обновить статистику"))
        self.add_question_btn.setText(_translate("MainWindow", "➕ Добавить вопрос"))
        self.broadcast_btn.setText(_translate("MainWindow", "📢 Создать рассылку"))
        self.stats_btn.setText(_translate("MainWindow", "📈 Подробная статистика"))
        self.activity_group.setTitle(_translate("MainWindow", "📅 Последняя активность"))
        self.activity_label.setText(_translate("MainWindow", "Загрузка данных активности..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_dashboard), _translate("MainWindow", "🏠 Дашборд"))
        self.control_group.setTitle(_translate("MainWindow", "Управление вопросами"))
        self.add_question_btn_2.setText(_translate("MainWindow", "➕ Добавить вопрос"))
        self.edit_question_btn.setText(_translate("MainWindow", "✏️ Редактировать"))
        self.delete_question_btn.setText(_translate("MainWindow", "🗑️ Удалить"))
        self.refresh_questions_btn.setText(_translate("MainWindow", "🔄 Обновить"))
        self.search_group.setTitle(_translate("MainWindow", "Поиск и фильтрация"))
        self.search_label.setText(_translate("MainWindow", "Поиск:"))
        self.question_search_input.setPlaceholderText(_translate("MainWindow", "Поиск по тексту вопроса..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_questions), _translate("MainWindow", "❓ Вопросы"))
        self.search_group_2.setTitle(_translate("MainWindow", "Поиск пользователей"))
        self.search_label_2.setText(_translate("MainWindow", "Поиск:"))
        self.user_search_input.setPlaceholderText(_translate("MainWindow", "Поиск по ID, имени или username..."))
        self.user_search_btn.setText(_translate("MainWindow", "🔍 Поиск"))
        self.show_all_users_btn.setText(_translate("MainWindow", "👥 Все пользователи"))
        self.manage_user_btn.setText(_translate("MainWindow", "👤 Управление пользователем"))
        self.ban_user_btn.setText(_translate("MainWindow", "🚫 Заблокировать"))
        self.unban_user_btn.setText(_translate("MainWindow", "✅ Разблокировать"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_users), _translate("MainWindow", "👥 Пользователи"))
        self.message_group.setTitle(_translate("MainWindow", "Сообщение для рассылки"))
        self.broadcast_message_input.setPlaceholderText(_translate("MainWindow", "Введите сообщение для рассылки..."))
        self.control_group_2.setTitle(_translate("MainWindow", "Управление рассылкой"))
        self.start_broadcast_btn.setText(_translate("MainWindow", "📢 Начать рассылку"))
        self.stop_broadcast_btn.setText(_translate("MainWindow", "⏹️ Остановить"))
        self.progress_group.setTitle(_translate("MainWindow", "Прогресс рассылки"))
        self.broadcast_status.setText(_translate("MainWindow", "Готов к рассылке"))
        self.results_group.setTitle(_translate("MainWindow", "Результаты рассылки"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_broadcast), _translate("MainWindow", "📢 Рассылка"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_statistics), _translate("MainWindow", "📈 Статистика"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_ai_dialogs), _translate("MainWindow", "💬 Диалоги с ИИ"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_ai_feedback), _translate("MainWindow", "⭐ Оценки ИИ"))
        self.bot_settings_group.setTitle(_translate("MainWindow", "Настройки бота"))
        self.bot_token_label.setText(_translate("MainWindow", "Токен бота:"))
        self.admin_ids_label.setText(_translate("MainWindow", "ID администраторов:"))
        self.db_group.setTitle(_translate("MainWindow", "Управление базой данных"))
        self.backup_db_btn.setText(_translate("MainWindow", "💾 Создать резервную копию"))
        self.create_admin_btn.setText(_translate("MainWindow", "👨‍💼 Создать администратора"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_settings), _translate("MainWindow", "⚙️ Настройки"))